### ISSUE TITLE
ES6/React support through babelify and reactify

### ISSUE THREAD

**Issue by Swaagie** [ferlores/mochify-istanbul#11]
Would be nice if the plugin would support these sets similar to coverify from the mochify suite, related: https://github.com/mantoni/mochify.js/issues/74

**Comment by Swatinem** [comment]
This will be fixed by #14 , you can then just specify `--instrumenter babel-istanbul` (you have to manually install the package though)

**Comment by ferlores** [comment]
version 2.2.0 is released with #14

**Comment by Swaagie** [comment]
osom thx :beers:
