### ISSUE TITLE
New dir default breaks our builds

### ISSUE THREAD

**Issue by mantoni** [ferlores/mochify-istanbul#17]
For some reason, a new default `dir` config was added in this commit:
https://github.com/ferlores/mochify-istanbul/commit/c92563e1e0247c35bd1b34bb1a306fcca3ec85e4

It's breaking all our builds now because Jenkins can't find the coverage file anymore. Please consider reverting this @Swatinem @ferlores.

**Comment by Swatinem** [comment]
Meh, sorry. PR to revert it is up. :-(

**Comment by mantoni** [comment]
Cool, thanks for the quick response!

**Comment by ferlores** [comment]
released on 2.2.2
